[package]
name = "repository"
version = "0.1.0"
authors = ["krampenschiesser <krampenschiesser@gmail.com>"]

[dependencies]
quick-protobuf = "0.6.0"
log = "0.4.1"
failure = "0.1.1"
uuid = "0.6.3"
chacha20-poly1305-aead = "0.1.2"