[package]
name = "repository"
version = "0.1.0"
authors = ["krampenschiesser <krampenschiesser@gmail.com>"]

[dependencies]
quick-protobuf = "0.6.0"
log = "0.4.1"
failure = "0.1.1"
uuid = { version = "0.6", features = ["v4"] }
chacha20-poly1305-aead = "0.1.2"
sha-1 = "0.7.0"
argon2rs = "0.2.5"